[network]
network = "Regtest"
listen_addr = "0.0.0.0:8233"
initial_peers = ["zebra-miner:8233"]
crawl_new_peers = false

[consensus]
checkpoint_sync = false

[state]
cache_dir = "/var/zebra/state"

[rpc]
listen_addr = "0.0.0.0:8232"
enable_cookie_auth = false

[mining]
internal_miner = false

[network.testnet_parameters.activation_heights]
NU5 = 1
